"""Adding User Table

Revision ID: 063383df9287
Revises: 526275b4f528
Create Date: 2024-11-04 18:25:55.637929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '063383df9287'
down_revision = '526275b4f528'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=32), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
