"""Adding User Table

Revision ID: 0c571a6d41c0
Revises: 063383df9287
Create Date: 2024-11-23 21:43:25.741356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c571a6d41c0'
down_revision = '063383df9287'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('logid', sa.Integer(), nullable=False),
    sa.Column('loguserid', sa.Integer(), nullable=True),
    sa.Column('registrationdate', sa.DateTime(), nullable=False),
    sa.Column('latestlogindate', sa.DateTime(), nullable=True),
    sa.Column('lastlogindate', sa.DateTime(), nullable=True),
    sa.Column('latestip', sa.String(length=100), nullable=True),
    sa.Column('lastip', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['loguserid'], ['users.id'], name=op.f('fk_logs_loguserid_users')),
    sa.PrimaryKeyConstraint('logid', name=op.f('pk_logs'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs')
    # ### end Alembic commands ###
