"""Adding User Table

Revision ID: 25456a3f69f9
Revises: 0c571a6d41c0
Create Date: 2024-11-25 13:20:08.459693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25456a3f69f9'
down_revision = '0c571a6d41c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salt', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('salt')

    # ### end Alembic commands ###
